### ISSUE TITLE
Install issue

### ISSUE THREAD

**Issue by white-jacob-dev** [decelis/BlazorGridStack#1]
Having an issue getting this to work in a fresh Blazor WASM project. I added the nuget package, but am not sure what imports/services I need to add to get it working with the markup you have shown. Any tips? Thanks!

**Comment by decelis** [comment]
No imports nor services needed, just adding the nugget package should be enough for this to work. Next update I should clarify this on the readme.

I haven't tried this project in WASM though, only on server mode. I will see if I can get to it, and if it is even possible to use it on Web assembly.

**Comment by decelis** [comment]
Blazor WASM is working correctly, the same as server mode. Updated the readme to clarify that you only need to import the main project files and that should be it. 

Added a new example project for blazor WASM too.
